apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-rl-shared-pvc
  labels:
    app: open-rl
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: enterprise-rwx
  resources:
    requests:
      storage: 1024Gi
