apiVersion: v1
kind: ConfigMap
metadata:
  name: dcgm-exporter-metrics
  namespace: default
data:
  default-counters.csv: |-
    ## GPU performance metrics,,
    # FieldID 100
    DCGM_FI_DEV_SM_CLOCK, gauge, SM clock frequency (in MHz).
    # FieldID 140
    DCGM_FI_DEV_MEMORY_TEMP, gauge, Memory temperature for the device.
    # FieldID 150
    DCGM_FI_DEV_GPU_TEMP, gauge, Current temperature readings for the device in degrees C.
    # FieldID 155
    DCGM_FI_DEV_POWER_USAGE, gauge, Power usage for the device in Watts.
    # Field ID 156
    DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION, counter, Total energy consumption for the GPU in mJ since the driver was last reloaded.

    # Utilization (the sample period varies depending on the product),,
    # FieldID 203
    DCGM_FI_DEV_GPU_UTIL, gauge, GPU utilization (in %).
    # FieldID 204
    DCGM_FI_DEV_MEM_COPY_UTIL, gauge, Memory utilization (in %).

    # Memory usage,,
    # FieldID 250
    DCGM_FI_DEV_FB_TOTAL, gauge, Total Frame Buffer of the GPU in MB.
    # FieldID 251
    DCGM_FI_DEV_FB_FREE, gauge, Framebuffer memory free (in MiB).
    # FieldID 252
    DCGM_FI_DEV_FB_USED, gauge, Framebuffer memory used (in MiB).
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-dcgm-exporter
  namespace: default
  labels:
    app.kubernetes.io/name: nvidia-dcgm-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-dcgm-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nvidia-dcgm-exporter
    spec:
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: Exists
      containers:
      - name: dcgm-exporter
        image: us-central1-artifactregistry.gcr.io/gke-release/gke-release/nvidia/gke-dcgm-exporter:4.4.1-4.6.0-gke.11@sha256:5c96863584d86494f1f677fcb15d567befa27b0f71b4a92606f8934fb583858e
        securityContext:
          privileged: true
        ports:
        - name: metrics
          containerPort: 9400
          protocol: TCP
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DCGM_EXPORTER_KUBERNETES
          value: "true"
        - name: DCGM_EXPORTER_LISTEN
          value: ":9400"
        - name: DISABLE_STARTUP_VALIDATE
          value: "true"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/nvidia/lib64"
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: nvidia-install-dir-host
          mountPath: /usr/local/nvidia
          readOnly: true
        - name: dcgm-metrics
          mountPath: /etc/dcgm-exporter
          readOnly: true
        - name: dev-fs
          mountPath: /dev
        - name: pod-resources
          mountPath: /var/lib/kubelet/pod-resources
          readOnly: true
      volumes:
      - name: nvidia-install-dir-host
        hostPath:
          path: /home/kubernetes/bin/nvidia
          type: DirectoryOrCreate
      - name: dcgm-metrics
        configMap:
          name: dcgm-exporter-metrics
      - name: dev-fs
        hostPath:
          path: /dev
      - name: pod-resources
        hostPath:
          path: /var/lib/kubelet/pod-resources
          type: DirectoryOrCreate
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: nvidia-dcgm-exporter-scraper
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nvidia-dcgm-exporter
  endpoints:
  - port: metrics
    interval: 10s
  targetLabels:
    metadata:
    - pod
    - container
    - node
