nameReference:
- kind: ConfigMap
  fieldSpecs:
  - kind: Sandbox
    path: spec/podTemplate/spec/containers/envFrom/configMapRef/name
- kind: PersistentVolumeClaim
  fieldSpecs:
  - kind: Sandbox
    path: spec/podTemplate/spec/volumes/persistentVolumeClaim/claimName
