apiVersion: batch/v1
kind: Job
metadata:
  name: tinker-rl-basic-job
  labels:
    app: tinker-rl-basic
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: tinker-rl-basic
    spec:
      serviceAccountName: open-rl-sa
      restartPolicy: Never
      containers:
      - name: tinker-rl-basic
        image: gcr.io/cdrollouts-sunilarora/tinker-cookbook:latest
        imagePullPolicy: Always
        resources:
          requests:
            ephemeral-storage: "10Gi"
            memory: "4Gi"
            cpu: "1"
          limits:
            ephemeral-storage: "10Gi"
            memory: "4Gi"
            cpu: "1"
        command: ["uv", "run", "--no-sync", "python", "-m", "tinker_cookbook.recipes.rl_basic", "base_url=http://open-rl-gateway-service:8000", "model_name=Qwen/Qwen3-4B-Instruct-2507"]
        env:
        - name: ENABLE_GCP_TRACE
          value: "1"
        - name: TINKER_BASE_URL
          value: "http://open-rl-gateway-service:8000"
        - name: TINKER_API_KEY
          value: "tml-dummy"
        - name: HF_HOME
          value: "/mnt/lustre/open-rl/huggingface"
        volumeMounts:
        - name: lustre-storage
          mountPath: /mnt/lustre
      volumes:
      - name: lustre-storage
        persistentVolumeClaim:
          claimName: open-rl-lustre-pvc
