apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lustre-rwx-1000mbps-per-tib
provisioner: parallelstore.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
