apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-rl-lustre-pvc
  labels:
    app: open-rl
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: lustre-rwx-1000mbps-per-tib
  resources:
    requests:
      storage: 1200Gi
