apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - custom-filestore-sc.yaml
  - 01-shared-pvc.yaml
  - 02-redis.yaml
  - 03-vllm.yaml
  - 04-gateway.yaml
  - 05-trainer-worker.yaml

images:
  - name: gcr.io/cdrollouts-sunilarora/open-rl-gateway
    newName: <your-gcr-path>/open-rl-gateway
  - name: gcr.io/cdrollouts-sunilarora/open-rl-server
    newName: <your-gcr-path>/open-rl-gateway
